name: Release Notes Generation

on:
  push:
    branches:
      - main

jobs:
  generate_release_notes:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Install git log parser
        run: npm install --save-dev gitlog-parser
      
      - name: Generate Release Notes
        run: |
          git log --pretty=format:"- %s [%h]" > RELEASE_NOTES.md

      # Additional steps to commit and push release notes to a designated location
      - name: Commit and push release notes
        run: |
          git add RELEASE_NOTES.md
          git commit -m "Generate release notes"
          git push origin main
