name: Dependency Updates

on:
  schedule:
    - cron: '40 19 * * 1-6'  # Run weekly on Monday at midnight

jobs:
  dependency_updates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Dependabot
        uses: dependabot/dependabot-core@v0.140.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: '/'
          package_manager: 'npm'
          update_schedule: 'weekly'
